name: Push image to ECR Registry | Rebuild docker image | Pull the image from ECR
on:
  push:
    branches: ["main"]

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Rebuild the image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ecr-apache:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: Push docker image to Amazon ECR Public
        env:
          REGISTRY: ${{ secrets.AWS_PUBLIC_REGISTRY }}
          REPOSITORY: ecr-apache
          IMAGE_TAG: latest
        run: |
          docker tag ecr-apache:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

